
## Camel-Weka

Camel-Weka moves this functionality one level up and provides Weka Data Minig as part of a https://camel.apache.org/[Camel,window=_blank] workflow. 
There are hundreds of components available in Camel. Data can be obtained from a wide array of data sources, then be passed on to the Camel-Weka 
component for analysis and desicion making with the results yet again being passed on to other components for further processing.  

### Consuming from file 

This first example shows how to read a CSV file with the file component and then 
pass it on to Weka. In Weka we apply a few filters to the data set and then pass it on to
the file component for writing. 

[source,java]
----
CamelContext camelctx = new DefaultCamelContext();
camelctx.addRoutes(new RouteBuilder() {

    @Override
    public void configure() throws Exception {
        
        // Use the file component to read the CSV file
        from("file:src/test/resources/data?fileName=sfny.csv&noop=true")
        
        // Convert the 'in_sf' attribute to nominal
        .to("weka:filter?apply=NumericToNominal -R first")
        
        // Move the 'in_sf' attribute to the end
        .to("weka:filter?apply=Reorder -R 2-last,1")
        
        // Rename the relation
        .to("weka:filter?apply=RenameRelation -modify sfny")
        
        // Use the file component to write the Arff file
        .to("file:target/data?fileName=sfny.arff")
    }
});
camelctx.start();
----

### Read + Filter + Write

The second example does the same as above without use of the file component.

[source,java]
----
CamelContext camelctx = new DefaultCamelContext();
camelctx.addRoutes(new RouteBuilder() {

    @Override
    public void configure() throws Exception {
        
        from("direct:start")
        
        // Use Weka to read the CSV file
        .to("weka:read?path=src/test/resources/data/sfny.csv")
        
        // Convert the 'in_sf' attribute to nominal
        .to("weka:filter?apply=NumericToNominal -R first")
        
        // Move the 'in_sf' attribute to the end
        .to("weka:filter?apply=Reorder -R 2-last,1")
        
        // Rename the relation
        .to("weka:filter?apply=RenameRelation -modify sfny")
        
        // Use Weka to write the Arff file
        .to("weka:write?path=target/data/sfny.arff");
    }
});
camelctx.start();
----
   
### Building a Model

To be done ...

### Persisting a Model

To be done ...

### Restoring a Model

To be done ...

### Predicting a Class

To be done ...



