
## Nessus API Concepts

The Nessus-Weka API is here to compliment rather than duplicate or reinvent functionality that is already present in Weka APIs.

The {java-api}/io/nessus/weka/Dataset.java[Dataset], which is the main entry point for everything, is a contextual
mutable, non-thread-safe entity. It is the holder of {weka-api}/weka/core/Instances.html[Instances], 
{weka-api}/weka/classifiers/Classifier.html[Classifier], {weka-api}/weka/classifiers/Evaluation.html[Evaluation].

Dataset holds multiple `Instances` one of which is the current, the others can be associated with a name and stashed for later use. Pushing the 
current `Instances` will put them on the stack. Popping `Instances` will remove them from the stack and make them current.

A `Classifier` will exist once loaded or built. An `Evaluation` will exist once the `Classifier` has been evaluated. 

Appart from getting `Instances`, `Classifier` or `Evaluation`, you'll find methods of this type ...

[source,java]
----
// Do something with Foo and return a Foo
Dataset applyToFoo(UnaryOperator<Foo> operator);

// Do something with with the Datasset and return a Foo
Dataset applyToFoo(Function<Dataset, Foo> function);

// Do something with Foo and return nothing
Dataset consumeFoo(Consumer<Foo> consumer);
----

These are very general extension points to the API, which allow you to get at the Weka primitives, do something with them (using the Weka APIs)
and then return the primitive back to the Dataset such that the next step can see the modified result from the previous step.

So for example, if you like to log the state of the current Classifier, you could do ...  

[source,java]
----
Evaluation eval = Dataset.create("data/sfny.arff")

        .buildClassifier("J48")
        
        .consumeClassifier(cl -> logInfo("{}", cl))
----

The {java-api}/io/nessus/weka/ModelPersister.java[ModelPersister] is another example of a `Consumer<Classifier>`. 
This time, defined externally rather than inline.

[source,java]
----
Dataset dataset = Dataset.create("data/sfny-train.arff")

        .buildClassifier("J48")
        
        .crossValidateModel(10, 1)
        
        .consumeClassifier(new ModelPersister("data/sfny-j48.model"))
----
                
The {java-api}/io/nessus/weka/NominalPredictor.java[NominalPredictor] is a good example of a `Function<Dataset, Instances>`. 
It accepts the `Dataset` so that it can get access to the `Classifier` and the `Instances` then does some number crunching 
and return new `Instances` that can then be passed on to the next step.

[source,java]
----
Dataset dataset = Dataset.create("data/sfny-test.arff")
        
        .applyToInstances(new NominalPredictor())
----

You get the idea, it is all about passing in functionality that is defined elsewhere. The `Dataset` has only very few "convenients" methods
that are so common that we prefer to use a simplified syntax rather than the functional approach.

These would be for example ...

[source,java]
----
Dataset dataset = Dataset.create("data/sfny-test.arff")
        
        .apply("StratifiedRemoveFolds -N 5")
        
        .buildClassifier("J48")
----
 
Under the hood, these invoke functions that return `Instances` and a `Classifier` respectively.

One last example perhaps. Instead of invoking the rename filter like this ...

[source,java]
----
Dataset dataset = Dataset.create("data/sfny-test.arff")
        
    .apply("RenameRelation -modify sfny-test")
----

you could equally well do this in Java like this ...


[source,java]
----
Dataset dataset = Dataset.create("data/sfny-test.arff")
        
        .applyToInstances((Instances ins) -> { 
            ins.setRelationName("sfny-test"); 
            return ins;
         })
----



                
                