= Nessus Weka
Thomas Diesler
:revnumber: {version}
:revdate: {localdate}
:source-highlighter: prettify
:imagesdir: img
:icons: font
:toc: left
:linkattrs:
:sectnums:

:scm-root: https://github.com/tdiesler/nessus-weka
:scm-branch: /tree/master
:scm-path: {scm-root}{scm-branch}

:java-api: {scm-path}/api/src/main/java
:data-part01: {scm-path}/part01/data

(C) 2020 The original authors.

Welcome to Nessus Weka. This is a collection of examples and tutorials related to the https://www.cs.waikato.ac.nz/ml/weka[Weka,window=_blank] data mining toolset.

Weka is tried and tested open source machine learning software that can be accessed through a graphical user interface, standard terminal applications, 
or a Java API. It is widely used for teaching, research, and industrial applications, contains a plethora of built-in tools for standard machine learning tasks, 
and additionally gives transparent access to well-known toolboxes such as scikit-learn, R, and Deeplearning4j. 

In this intro, we'll show you how to get started with simple data mining tasks and how to incorporate these into larger https://camel.apache.org[Apache Camel,window=_blank] workflows.

include::chap01/index.adoc[]

include::chap02/index.adoc[]

include::chap03/index.adoc[]

include::chap04/index.adoc[]

include::chap05/index.adoc[]

## Feedback

For feedback, suggestions, request, etc. please go to  ...

* {scm-root}/issues[Issue Tracker,window=_blank]
* {scm-path}/docs/src/guide[Documentation Sources,window=_blank]
* {scm-path}/part01/src/test/java/io/nessus/weka/test/part01[Example Code,window=_blank]

## Resources

* https://www.cs.waikato.ac.nz/ml/weka/book.html[Practical Machine Learning Tools and Techniques,window=_blank]
* https://www.cs.waikato.ac.nz/ml/weka/courses.html[Machine Learning Courses,window=_blank]
* https://waikato.github.io/weka-wiki/documentation/[Weka Documentation,window=_blank]
* {scm-root}[Nessus-Weka,window=_blank]

